### PR TITLE
feat(lang): Add Italian translation

### PR DESCRIPTION
**Pull request by damianopetrungaro**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@bcoe please read it if you have time, it's more than 20 days old 😄

**Comment by stevemao** [comment]
This should probably be good to go... Thanks @damianopetrungaro !

**Comment by bcoe** [comment]
@damianopetrungaro awesome \o/ thank you so much for the contribution (and sorry for the slow turnaround). It's live now.

**Comment by damianopetrungaro** [comment]
@stevemao @bcoe no worries 😄  If you have time take a look to the issue i opened days ago  😝

**Pull request merged**
