### PR TITLE
fix: add spec compliant parser

### PR DESCRIPTION
**Pull request by olstenlarck**
It was in work for few months, but last night i released v2 of it. I'm using conventional commits for year or two, and thanks for that specification. I also have badge to the spec in most of my repos.

Let me know if something is not okey.

### CODE REVIEW

**Comment by olstenlarck** [comment]
I kinda intentionally did it that way, because you can squash merge it... But ok.

**Comment by damianopetrungaro** [comment]
Hey, @olstenlarck let's reword the commit and let's merge it!

**Comment by olstenlarck** [comment]
Oooh, i forgot about that, thanks for reminder ; )

**Comment by damianopetrungaro** [comment]
Ahaha no worries, I think that `docs` is better than `fix` by the way, could you please update it on the fly?

So we can merge it!

**Comment by olstenlarck** [comment]
Ooookey :laughing:

**Comment by damianopetrungaro** [comment]
👍  cool!
Thank you for your time @olstenlarck !

Sorry for the 🏓 but we finally merge it!

**Comment by olstenlarck** [comment]
Ah, no problem :five:

**Pull request merged**
