### PR TITLE
feat(showcase): add angular and karma

### PR DESCRIPTION
**Pull request by stevemao**
Minor format tweaks

### CODE REVIEW

**Comment by bcoe** [comment]
@stevemao looks good to me 👍 I think we might want to flag a core maintainer from each project on this pull request, to make sure they're cool with being added to the list -- I'm sure they most likely will be.

**Comment by stevemao** [comment]
CC @dignifiedquire @IgorMinar @pkozlowski-opensource

**Comment by staltz** [comment]
I'm cool. Thanks for adding it :)

**Comment by jameswomack** [comment]
Is there anything left on this PR?

**Comment by stevemao** [comment]
@jameswomack Should be good to merge

**Comment by xeruf** [comment]
This was only added to a particular spanish beta and is neither in the current english nor spanish version :/

**Pull request merged**
