### PR TITLE
fix: link to Angular Commit Guidelines

### PR DESCRIPTION
**Pull request by JaKXz**
Using a commit hash so the link isn't incorrect as [long as] the repo lives :)

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Welcome @JaKXz ! 
Thank you for your first contribution 😄 
Could you please update all the links pointing to the wrong Angular URL in the project and update it?

If should be pretty easy, let me know if you haven't time to do it 😄

**Comment by JaKXz** [comment]
Fixed :)

**Comment by damianopetrungaro** [comment]
@bcoe I just noticed that @JaKXz  is pointing to `angular/angular.js` repo.
`angular/angular` repo have the same content too. ([link here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit))
Which one would you suggest to use?
I'd prefer `angular/angular`

**Comment by bcoe** [comment]
I agree let's use the `angular` repo, I think that's more correct. work for you @JaKXz?

**Comment by JaKXz** [comment]
on it!

**Comment by JaKXz** [comment]
@bcoe @damianopetrungaro done!

**Comment by damianopetrungaro** [comment]
Cool, look good to me!
Thank you @JaKXz for your first contribution!

**Pull request merged**
