### PR TITLE
feat(specs): Introduce 'improvement' type

### PR DESCRIPTION
**Pull request by damianopetrungaro**
@stevemao let me know what do you think.
I saw in another PR that we'll use `noun` instead of `verb`, so `improvement` is used instead of `improve`

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@stevemao @bcoe take a look here

**Comment by ungoldman** [comment]
I think this concept is already covered by `refactor` (see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type), which should not trigger a version bump.

**Comment by damianopetrungaro** [comment]
Refactor means no breaking changes are made.
Improvement may break APIs but it's not a feature neither a fix.

**Comment by bcoe** [comment]
@damianopetrungaro sorry for the slow turnaround, don't have a ton of time for open-source these days unfortunately.

There's nothing in the spec that stops you from using the `improvement` verb; but functionality it's fairly similar to `feat` and I think at this time I'd like to avoid adding it to the spec itself.

If you'd like to add it as a recommended verb to the `Others:`, perhaps we can make the recommendation here.

**Pull request closed without merging**
