### PR TITLE
v1.0.0-beta.2 spanish translation

### PR DESCRIPTION
**Pull request by archemiro**
Hi, very nice project!

I've been sitting on this translation for a week waiting to complete the v1.0.0-beta and v1.0.0-beta.1, but haven't have much time for completing it so I hope it is ok with you to have only the beta.2 translated for now because It might take me a while to complete the other translations, maybe someone else can pick up from here to complete them.

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Hey @archemiro congrats for your first PR to the project!
Unfortunately, it's impossible to merge right now due to conflicts, could you please rebase it?

Let's see what @bcoe  and @stevemao suggest for the translation for old versions, imho it's ok with the last beta version will be hard in future to keep all the translations updated 😄

**Comment by damianopetrungaro** [comment]
@archemiro  If you need help for the rebase feel free to ask :D

**Comment by archemiro** [comment]
@damianopetrungaro I'm going to need some help with the rebase, I'm not very familiar with it, already search about it but can't figure out exactly what to do in this case to clean my commit history.

**Comment by damianopetrungaro** [comment]
@archemiro so the final result that we want to obtain is to remove all the other commit except your one.

Enter `git rebase -i HEAD~5`
This will allow you to enter into an rebase interactive mode.
Now you have superpowers  😄 

At the bottom of the command, you'll find all the instructions and options that you can use 😄 

You'll see something like this:
```
pick 46c02db    fix: doc cleanup
pick c4ff231    feat(lang): update Chinese translations to 1.0.0-beta.2
pick 81e7cce    feat(lang): v1.0.0-beta.2 spanish translation
pick 0037c18    feat: add massive to projects listing
pick 391457d    fix: Redirect English link to beta.2
```

Now let's drop all the unuseful commit 😄 
Update it to this

```
drop 46c02db    fix: doc cleanup
drop c4ff231    feat(lang): update Chinese translations to 1.0.0-beta.2
pick 81e7cce    feat(lang): v1.0.0-beta.2 spanish translation
drop 0037c18    feat: add massive to projects listing
drop 391457d    fix: Redirect English link to beta.2
```
_you may also enter only `d` and not `drop`_

And you should only have your commit added to your branch 😄 


Now let's start rebase to the upstream:

Simply:
```
git fetch upstream
git checkout archemiro:lang-spanish
git rebase upstream/master
```
And then let's push with the -f to your remote branch 😄 (git push origin archemiro:lang-spanish -f)

If you have any problem or want to know more about something let me know, i'll help you 😄

**Comment by archemiro** [comment]
@damianopetrungaro I think I got it 😄 . Thank you for the detailed explanation. Also removed the remaining files without translation.

**Comment by damianopetrungaro** [comment]
WOW @archemiro great job! Now it looks perfect!
For me it's good! Let's wait also someone other opinions about removing not-maintained translations.
I hope that the entire flow was clear! Ping me privatly if you want also other explainations 😄

**Pull request merged**
